### ISSUE TITLE
RTKPOST: allow input of multiple SP3 files

### ISSUE THREAD

**Issue by fgnievinski** [tomojitakasu/RTKLIB_bin#9]
When doing PPP in a 24-hour observation file, the last 15 minutes diverge.  A manual workaround is to merge the precise ephemeris file for the following day.  A more automatized solution would be allowing the input of multiple SP3 files (as a comma separated list).  Thanks.

**Comment by tomojitakasu** [comment]
Use "*" (wild-card) in the input file path to select multiple SP3 files.
Or include time keywords in the input file path and set the start time and the end time. In this case, RTKPOST automatically reads the next day's SP3 file (Strictly, it additionally reads the SP3 file containing the ephemeris at end_time + 1H).

**Comment by fgnievinski** [comment]
thanks, I was selecting multiple files in the file browser dialog, will do as you say.
